services:
  - type: web
    name: custom-bluesky-client
    env: node: "20"
    region: frankfurt
    plan: free
    buildCommand: "yarn install --frozen-lockfile && yarn build"
    startCommand: "yarn start"
    healthCheckPath: "/"
    envVars:
      - key: NODE_ENV
        value: production
